### ISSUE TITLE
An Exception happens in a check will make the Runner not available for the rest of the analysis

### ISSUE THREAD

**Issue by tromai** [oracle-samples/macaron#132]
**Description**
This issue is discovered together with issue #131 . When an exception happens, we could not properly re use the Runner which run that check. This will make the rest of the analysis failed with the following error message:
```
2023-03-29 12:04:07,600 [CRITICAL] Could not find any available runners. Stop the analysis...
```
**Reproduce**
We can run the analysis against a sample config where the repository mentioned in #131 (https://github.com/java-json-tools/json-patch) is one of the dependencies. For example:
```
target:
  id: apache/maven
  path: https://github.com/apache/maven

dependencies:
- id: exception-happen-repo
  path: https://github.com/java-json-tools/json-patch
- id: The analysis will failed to run against this dependency because the Runner is not available.
  path: https://github.com/ben-manes/caffeine.git
```
